### ISSUE TITLE
Implement TLS interception for HTTPS origination from the application

### ISSUE THREAD

**Issue by vadimeisenbergibm** [eclipse/microprofile-service-mesh#12]
In some cases, the apps use libraries that use HTTPS only. In this cases, Istio can only report and control source and destination IP, and also SNI. Istio cannot report and control paths, headers, methods, content (L7).

If Istio will be able to perform TLS interception, Istio will be able to provide full support for HTTPS traffic.

**Comment by Emily-Jiang** [comment]
As of today's call, we agree this issue is beyond the scope of MP. This remains the limitation of Istio sidecar proxy.

**Comment by Emily-Jiang** [comment]
Istio can utilise MP programming model for https communications, e.g. MP Fault Tolerance etc.
