### ISSUE TITLE
MP OpenTracing with Istio 1.0 

### ISSUE THREAD

**Issue by ykoyfman** [eclipse/microprofile-service-mesh#40]
I'm experimenting with OpenTracing and Istio and I'd like to understand whether the results I'm seeing are the expected behavior with regard to how headers and spans are propagated in the context of Istio with the JAX-RS REST client.   In short, I have three microservices, each one in an OpenLiberty container (with sidecar).  The call sequence is:
ingress-gateway --> A --> B --> C.   When viewing the spans in Jaeger or Zipkin I expect to see a hierarchical view, with a "tree" style visualization showing at a glance what the call sequence looks like.  Here's what I see in my experiment - showing the same trace in both Jaeger and then Zipkin as I have both running in the cluster:

![image](https://user-images.githubusercontent.com/13653608/54454762-96789d00-4730-11e9-9069-a9ad720ef130.png)

In Zipkin:

![image](https://user-images.githubusercontent.com/13653608/54455027-2dddf000-4731-11e9-853f-0871e22026cc.png)

(In this example, the "instrument-craft-shop" service makes two POST calls to "maker-bot" which in turn makes POST calls to the "dbwrapper" service.)

The Bookinfo example (https://istio.io/docs/tasks/telemetry/distributed-tracing/) shows a clear parent/child relationship between services that are calling each other - is that possible to achieve with OpenTracing/Microprofile and JAX-RS client?  (Jaeger shows this kind of hierarchy only within the istio-* services, while Zipkin does not.) When I look at headers I see that x-b3-traceid is preserved across all calls in the sequence but x-b3-parentspanid is unique for every call.  

The code is available here https://github.com/ykoyfman/tracing-demo  (the places where the REST client is being used is https://github.com/ykoyfman/tracing-demo/blob/master/maker-bot/src/main/java/com/sebastian_daschner/maker_bot/Persist.java and in https://github.com/ykoyfman/tracing-demo/blob/master/instrument-craft-shop/src/main/java/com/sebastian_daschner/instrument_craft_shop/control/MakerBot.java.  I did manually add the x-request-id header to all calls, following the bookinfo example of header propagation. 

Istio 1.0.6
OpenLiberty 19.0.0.2 / mpOpenTracing-1.2

**Comment by kenfinnigan** [comment]
I believe the hierarchy isn't present because the parentspanid is being created fresh on each request.

That needs to be passed from one call to the next.

I don't think that happens with the JAX-RS Client. It will happen by default with the MP REST Client with the latest version of MP 2.2, but I'm not sure OpenLiberty supports that yet

**Comment by ykoyfman** [comment]
@kenfinnigan  Thanks for the suggestion.  I tried that initially but it didn't work: when I attempted to set the x-b3-parentspanid manually on each outgoing REST call (keeping track of the value from the incoming headers) it broke the trace sequence (i.e. would not show up Jaeger).  I don't know if it's OpenTracing or envoy but something else is trying to modify that header and when I log the value in the next service in the chain the value is corrupted.  Here's what I see.

Say the incoming headers have
`x-b3-spanid: 377a3f74e38d5d4f` 
so now I save that value and propagate it to the call that makes the REST client call to the next service in the chain.  I would do something like:

`target.request().header("x-b3-parentspanid", parentId).post(Entity.json(requestBody));`

However..when I log the headers on the receiving end it looks like this

`x-b3-parentspanid: 377a3f74e38d5d4f,377a3f74e38d5d4f`

I checked to make sure I'm not inserting the value twice.  In fact, even when I set the x-b3-parentspanid and leave it blank I get a comma added to the value when I read it back on the receiving service, so it looks something like `x-b3-parentspanid:  ,377a3f74e38d5d4f`

My interpretation of this behavior is that by trying to set that field manually I'm interfering with some OpenTracing / envoy code that expects to have control of x-b3-* propagation.

**Comment by kenfinnigan** [comment]
It appears to be an issue with OpenLiberty, as I know I've done this same thing with Thorntail without issue.

I'd suggest opening an issue with OpenLiberty directly

**Comment by ykoyfman** [comment]
@kenfinnigan Thanks for confirming it works with Thorntail, I'll open an issue in the OL tracker. Btw, do you know if the `TracingProperties.CHILD_OF` property described here https://github.com/opentracing-contrib/java-jaxrs#tracing-client-requests is supposed to be supported in MicroProfile REST clients?

**Comment by kenfinnigan** [comment]
I don't know

**Comment by fmhwong** [comment]
@ykoyfman Have you tried to run your code in OL only?  i.e Not using Istio?

**Comment by ykoyfman** [comment]
I've reproduced this outside of Istio, details here:  https://github.com/OpenLiberty/open-liberty/issues/6936

**Comment by kenfinnigan** [comment]
Will close as not related to MP
